import json
import re

raw_lyrics = json.load(open('full_genius_lyrics.json', encoding='utf-8'))

def clean_txt(t):
    return re.sub(r'[^a-zA-Z0-9äöüÄÖÜß]', '', t).lower()

def check_quote_in_track(quote, track_text):
    # Split quote by slash or ellipsis if multi-line
    parts = [p.strip() for p in re.split(r'[/–—]', quote) if p.strip()]
    track_clean = clean_txt(track_text)
    for p in parts:
        p_clean = clean_txt(p)
        if len(p_clean) >= 4 and p_clean not in track_clean:
            return False, p
    return True, ""

reviews_de = {
    "01": """<p>Das Album eröffnet mit der Inszenierung des Ursprungsmythos: <strong>„1996“</strong> markiert den biografischen und psychologischen Nullpunkt der Persona. Eingerahmt von mediterraner Hitze und der schwebenden Erwartung eines Sommers auf Ibiza entfaltet Tua das Leitmotiv des Werks: Der <span class="lyric-quote-highlight">„Panoramablick übers Paradies / Während warme Luft auf dem Garten liegt“</span> ist kein Ort inneren Friedens, sondern die erhabene Bastion eines Ichs, das die Welt nur aus sicherer Distanz erträgt. Doch bereits im zweiten Teil bricht das Verdrängte unaufhaltsam ein: <span class="lyric-quote-highlight">„Etwas fehlt, vielleicht ist es aufgewacht / Das Gegenteil, das Außerhalb“</span>. Das heraufziehende Rauschen in den Palmen kündigt den existenziellen Mangel an.</p>
<p>Im sakral aufgeladenen Refrain (<span class="lyric-quote-highlight">„Ob die Welt hält, was sie verspricht? / Steig' herab in strahlendem Licht / Und ganz in Weiß gekleidet“</span>) wird der narzisstische Abstieg als messianischer Auftritt inszeniert. Doch das Outro vollzieht die schonungslose Demaskierung: Als <span class="lyric-quote-highlight">„Ikarus, Fantasieprodukt / Entfliehst dem Druck hoch in die Fieberluft“</span> flieht die Kunstfigur vor der Realität. Der Flug über den <span class="lyric-quote-highlight">„tiefsten Bruch“</span> ist keine Freiheit, sondern die manische Flucht vor dem unausweichlichen Aufprall.</p>""",

    "02": """<p>In <strong>„Wiedersehen“</strong> vollzieht der Protagonist den radikalen Bruch mit seiner Herkunft und formuliert sein rücksichtsloses Autarkie-Credo. Mit schnoddriger Verachtung wischt das Ich alle moralischen Bewertungen der alten Heimat beiseite: <span class="lyric-quote-highlight">„Dann bin ich jede Story, die dein Dorf sich erzählt / Weine keinem eine scheiß Träne hinterher / Wo ich hingehe, ist das Licht dir zu hell“</span>. Die Arroganz fungiert als hermetischer Schutzschild gegen Schuld und Beschämung.</p>
<p>Die Grausamkeit der Abspaltung erreicht im zweiten Vers ihren Höhepunkt: <span class="lyric-quote-highlight">„Ich hab' dich nie geliebt, sondern war dich nur gewohnt / Ich wein' dir nicht mal eine scheiß Träne hinterher“</span>. Intimität wird nachträglich entwertet, um jeden Trennungsschmerz zu ersticken. Auf der Mittelmeerfähre stehend, blickt der Protagonist im Outro auf die schäumende Heckwelle und pervertiert die Seligpreisungen in ein raubtierhaftes Gesetz: <span class="lyric-quote-highlight">„Ich steh' auf einer Fähre übers Mittelmeer / Seh' der weißen Spur im Wasser hinterher / Selig sind die Diebe / Ich nehme, was ich kriege“</span>. Bindung ist für ihn kein Dialog, sondern ein Beutezug vor dem nächsten Transit.</p>""",

    "03": """<p><strong>„GluiV“</strong> seziert die vulgäre Oberfläche des Jetset-Materialismus und transformiert Markensymbole in ein psychologisches Exoskelett. Die repetitive Stakkato-Hook <span class="lyric-quote-highlight">„G, Louis V, Bauchtasche, Kokain, ich fick' alle“</span> ist kein naiver Flex, sondern die krampfhafte Beschwörung unverwundbarer Allmacht. Der Protagonist definiert sich über kinetische Rastlosigkeit und chemische Zufuhr (<span class="lyric-quote-highlight">„Immer in Bewegung, immer im Dienst / Vitamin Zieh“</span>), um jedes Innehalten zu verhindern.</p>
<p>Die Szenerie im <span class="lyric-quote-highlight">„Marmorfliesen im Airbnb / Ihr Leihparadies“</span> entlarvt die Austauschbarkeit der Akteure. Hinter der Prahlerei bricht im Pre-Hook die nackte Kränkung durch: <span class="lyric-quote-highlight">„Und trotzdem, denn ich bin nicht ihr Typ / Nur der Typ, der den Stoff bringt, glaubt sie“</span>. Die glamouröse Fassade scheitert daran, die fundamentale Entfremdung zu überdecken – das Subjekt bleibt der bloße Dienstleister der Betäubung.</p>""",

    "04": """<p>In <strong>„Dachterrasse“</strong> kippt der Rausch in die bleierne Kälte der Morgendämmerung. Vom Dach einer Luxusresidenz blickt der Protagonist auf die schlafenden Hotelburgen herab – isoliert in der Illusion, <span class="lyric-quote-highlight">„Auf der Dachterrasse weit oben, allem überlegen“</span> zu sein. Doch im Pre-Hook bricht das fundamentale Kindheitstrauma ungefiltert durch: <span class="lyric-quote-highlight">„Bis keiner mehr da ist, so wie damals meine Mutter / Glorreich, glorreich geh'n wir unter“</span>. Der narzisstische Höhenflug wird als desperate Bewältigung frühkindlicher Verlassenheit demaskiert.</p>
<p>Der zweite Vers formuliert die absolute Abwehr von Intimität: <span class="lyric-quote-highlight">„Wenn du wüsstest, was ich denk', ich will nicht, dass du mich kennst / Diese Existenz ist nicht mehr als ein One-Night-Stand“</span>. Das Mantra des Refrains – <span class="lyric-quote-highlight">„Man muss aufhör'n, wenn's am besten ist / Denn mit der Zeit wird alles lächerlich“</span> – ist kein Zeichen von Vernunft, sondern die panische Flucht vor dem Moment, in dem die Maske verrutscht und die eigene Bedürftigkeit sichtbar wird.</p>""",

    "05": """<p><strong>„Für mich“</strong> legt das erotisch verbrämte Machtgefüge narzisstischer Bindung offen. Hinter der intimen Kulisse (<span class="lyric-quote-highlight">„Hinter einer blauen Tür / Unter einem Baldachin aus Seide / Will das Mondlicht Haut berühr'n / Auf der Innenseite deiner Beine“</span>) inszeniert das Ich die sexuelle Begegnung als totalen Unterwerfungsakt: <span class="lyric-quote-highlight">„Unter dir bin ich außer mir / Bis du klingst, als würdest du verzweifeln / Lass mich das Größte für dich sein / Lass es das Größte für mich sein, das ich erreiche“</span>. Intimität ist hier kein Raum für Augenhöhe, sondern der exklusive Maßstab des eigenen narzisstischen Geltungsdrangs.</p>
<p>Die Hook fordert die vollständige Selbstaufgabe des Partners (<span class="lyric-quote-highlight">„Gib dich auf, auf für mich / Geb' mich, geb' mich auf, auf für dich“</span>), während das Ich eine scheinbare Gegenseitigkeit nur vorspiegelt. Im zweiten Vers formuliert Tua die unheilvolle Symbiose in einem der prägnantesten Vergleiche des Albums: <span class="lyric-quote-highlight">„Wir gehör'n zusamm'n wie Größenwahn und Scheitern“</span>. In der Bridge begründet das Ich seinen Kontrollzwang mit mathematischer Unerbittlichkeit: <span class="lyric-quote-highlight">„Was ich brauch', ist Sicherheit / Durch null kann man nicht mehr teil'n“</span>.</p>""",

    "06": """<p>In <strong>„Rette mich nicht“</strong> verweigert das Ich jede Form partnerschaftlicher Rettung und zelebriert seine autodestruktive Autonomie. In rastloser Manie rast der Protagonist durch die Nacht (<span class="lyric-quote-highlight">„Immer unterwegs mit den Feinden / Adern voller Gift / Kickdown, rauchende Reifen / Mercadona, Parkplatz-Drift“</span>), um die Grenze des Erträglichen zu testen. Das Hilfsangebot des Gegenübers wird mit zynischem Stolz abgewehrt: <span class="lyric-quote-highlight">„Um mich zu ruinier'n, brauch' ich keinen / Das schaff' ich auch alleine“</span>.</p>
<p>Die Hook deklariert die totale emotionale Verflachung: <span class="lyric-quote-highlight">„Rette mich nicht / Ich hass' dich nicht, du bist mir bloß egal / Ich laufe durch das Niemandsland in überlebensgroß / Tauche in die Zwielichter und hoff', ich geh' verlor'n“</span>. Im zweiten Vers wendet sich das Ich direkt an die verlassene Partnerin (<span class="lyric-quote-highlight">„Ich bin das Problem und ich weiß es / Nur macht es das nicht kleiner, Gianna“</span>), ehe die Bridge jede romantisierte Bindung zerschlägt: <span class="lyric-quote-highlight">„Wir leben nicht in derselben Realität / Du liebst mich nicht, du kriegst nur nicht, was dir fehlt / Du solltest mich einfach vergessen / Wie leichte Versprechen auf weißen Tabletten in Zeitraffer-Nächten“</span>.</p>""",

    "07": """<p><strong>„Leicht“</strong> ist die Chronik einer abgestumpften Affektabflachung im hedonistischen Nachtleben. Aus purer Trägheit gerät der Protagonist in eine Villa-Party und beginnt eine flüchtige Begegnung ohne jede emotionale Beteiligung: <span class="lyric-quote-highlight">„Fang' zu flirten an, nur aus Routine / Finde sie nicht mal besonders heiß / Doch geteiltes Leid ist halbes Leid“</span>. Das unterlegte englische Sample (<span class="lyric-quote-highlight">„Trying to feel alright all the time“</span>) fungiert als resignatives Mantra.</p>
<p>Im zweiten Vers tritt die Dissoziation offen zutage: <span class="lyric-quote-highlight">„Blauer als die Scheinwerfer im Pool / Schaue mir von weit weg dabei zu / Alles fühlt sich als, als wär es geschäftlich / Echt ist nur die Leere, seit du weg bist“</span>. Die finale Entsorgung der Intimität vollzieht sich im Outro mit administrativer Gleichgültigkeit an der Taxitür: <span class="lyric-quote-highlight">„Sie will ballern, ich schenk' ihr ein Gramm / „Meld dich“, sagt sie, ich denke nicht dran / „Danke für den nicen Abend“, sagt sie / „Ja“, sag' ich und schließ' die Tür von ihr'm Taxi“</span>.</p>""",

    "08": """<p><strong>„Höhenflug + Tiefenrausch“</strong> markiert den unausweichlichen dopaminergen Absturz und das depressive Epizentrum des Werks. In beklemmender Plastizität verdichtet Tua den Selbstekel: <span class="lyric-quote-highlight">„Bin ein alter Schwamm, den man mal wechseln müsste / Ich schreib' mich minus eins auf die Gästeliste / Wurde von 'nem Sorgenkind zum Sorgenking“</span>. Die manische Energie ist restlos verbrannt; die Couch wird zum schwarzen Loch, das den erstarrenden Körper verschlingt (<span class="lyric-quote-highlight">„Die Couch schluckt mich und spuckt mich nie mehr aus / Alle Energie verbraucht / Falle durch die Welt, bin im Fiebertraum / Zwischen Höhenflug und Tiefenrausch“</span>).</p>
<p>Die grausame Ehrlichkeit im zweiten Vers demaskiert die Funktion früherer Bindungen: <span class="lyric-quote-highlight">„Sorry, dass ich dir so lang was vorgemacht hab' / Hing nur mit dir rum, weil ich dich so gehasst hab'“</span>. In der Badewanne liegend, versucht das Ich seine somatische Existenz aufzulösen (<span class="lyric-quote-highlight">„Hundert Meter tief in mein'n Augenhöhl'n / Lieg' in der Wanne, versuch' mich aufzulösen“</span>), während die Wände im leeren Heldensaal unerbittlich näher rücken (<span class="lyric-quote-highlight">„Hör' jetzt Stimmen schweigen, der Heldensaal ist leer / Unendlich Langeweile, die Wände kommen näher“</span>).</p>""",

    "09": """<p><strong>„Dopamin Spike“</strong> zelebriert den Triumph der biochemischen Illusion über die Realität. Mit der ersten chemischen Welle wird jede Verpflichtung getilgt: <span class="lyric-quote-highlight">„Dopamin-Spike und mein Herz rast / Seit ich es dir nicht mehr hinterhertrag' / Baller' mich höher als die Schwerkraft / Hatte 1g, lege mehr nach / Jeder Satz hört sich legendär an / Und muss gar nicht wahr sein / Muss sich nur so anfühl'n“</span>. Tua formuliert hier das Manifest des postfaktischen Hedonismus: Wahrheit ist irrelevant, solange der Neurotransmitter feuert.</p>
<p>Die <span class="lyric-quote-highlight">„Sonnenbrille bei Nacht, denn ich bin in der Matrix“</span> schützt nicht nur die Mydriasis der Pupillen, sondern schirmt das Ich vor der Realität ab. Im zweiten Vers greift der Protagonist die moralische Integrität der Nüchternen an: <span class="lyric-quote-highlight">„High auf Moral, doch ich glaub's nicht / Denn es ist deine Wahrheit / Wegen der du so taub bist / Solang, bis du drauf bist“</span>. Ethik wird als bloße feige Selbstaufgabe entwertet.</p>""",

    "10": """<p>In <strong>„Amnesia“</strong> explodiert die klaustrophobische Enge des Ibiza-Nachtlebens in roher, choreografierter Gewalt. Tua zeichnet die sensorische Reizüberflutung im Club mit schonungsloser Haptik: <span class="lyric-quote-highlight">„Diese EDM-Mucke hier drinne ist furchtbar / Ich hass' diese Nacht und ich hass' ihr'n Geburtstag / Lächel gezwung'n, renne aufs Klo, um zu koksen und weil ich Durst hab' / Wasser mit Salz, bitterer Schleim in mei'm Hals“</span>. Das erzwungene Lächeln auf der Geburtstagsfeier bricht unter dem akustischen Beschuss der EDM-Bässe zusammen.</p>
<p>Der Konflikt mit einem britischen Touristen wird zur ersehnten Entlastung: <span class="lyric-quote-highlight">„Du kommst mir grade recht / Junge, willst du, dass ich dir die Nase brech'?“</span>. Die Schlägerei ist kein Unfall, sondern die gezielte somatische Entladung unerträglicher innerer Spannungen. Im Moment des Club-Höhepunkts (<span class="lyric-quote-highlight">„Warte auf den Drop und die CO2-Kanon'n / Kalter Rauch, reiß' mich los / Und tret' ihm in sein Declan-Rice-Trikot“</span>) verschmelzen Bass-Drop und körperliche Brutalität zum finalen Exzess.</p>""",

    "11": """<p><strong>„Kaputt“</strong> bildet das monumentale Finale und die radikale Selbstdemontage des Albums. Eingerahmt von der Totenstarre des Intros (<span class="lyric-quote-highlight">„Springmesser-Tattoo auf meiner Brust / Tu nicht so, als hast du nichts gewusst / Hand aufs Herz, ich spüre kein'n Puls / Deine Liebe blieb für immer im August“</span>) steht der Protagonist am Hafen zwischen Bauruinen und Schutt. Das Bild des verendeten Tieres spiegelt den Ruin des eigenen Charakters: <span class="lyric-quote-highlight">„Ein toter Hund liegt zwischen dem Bauschutt / Ich war nie viel mehr als 'ne Behauptung“</span>.</p>
<p>Die namensgebende Formel <span class="lyric-quote-highlight">„Was ich berühr', das geht kaputt / Ganzes Leben zerleg' ich zu Schutt“</span> artikuliert den Fluch des malignen Narzissmus: Die Unfähigkeit, Verbindung einzugehen, ohne sie zu vernichten. Der Schlusssatz des Albums – <span class="lyric-quote-highlight">„Und ich kam immer davon, aber niemals an“</span> – verweigert jede billige Erlösung. Das Werk endet in der glasklaren, unerbittlichen Erkenntnis der eigenen ewigen Entwurzelung.</p>"""
}

# Run rigorous verification
all_passed = True
for t_num in sorted(reviews_de.keys()):
    rev = reviews_de[t_num]
    track_text = raw_lyrics[t_num]["full_text"]
    
    # Extract all quotes inside lyric-quote-highlight
    quotes = re.findall(r'<span class="lyric-quote-highlight">„?(.*?)“?</span>', rev)
    for q in quotes:
        # Strip German quotes if present
        q_clean = q.replace('„', '').replace('“', '').replace('"', '').replace('&quot;', '')
        ok, bad_part = check_quote_in_track(q_clean, track_text)
        if not ok:
            print(f"[ERROR] Track {t_num} has INVALID quote: '{bad_part}' from full quote '{q}'")
            all_passed = False
        else:
            print(f"[OK] Track {t_num} quote verified: '{q_clean[:40]}...'")

if all_passed:
    print("\n>>> ALL 11 GERMAN REVIEWS PASS 100% VERBATIM LYRICS VERIFICATION! <<<")
else:
    print("\n>>> VERIFICATION FAILED! <<<")
